version: '3'
services:
  dev:
    platform: linux/x86_64
    build:
      context: ../../
      dockerfile: ./docker/dev/Dockerfile
    tty: true
    command: bash
    working_dir: /app
    volumes:
      - ../..:/app
