version: '3'
services:
  dev:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    volumes:
      - .:/app
    tty: true
    working_dir: /app
    command: /bin/bash